version: '3.6'
services:
 rabbitmq:
  image: rabbitmq
  container_name: rabbitmq
  ports:
   - "5673:5672"
   - "25676:25676"
  environment:
   RABBITMQ_DEFAULT_USER: user
   RABBITMQ_DEFAULT_PASS: password

  
